{% set name = "area-detector-handlers" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20339216fb1e78fe756a04f8ddff59b97edc9a88438ea9c26e245cba42d20592

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - entrypoints
    - h5py
    - pandas
    - tifffile >=2020.8.25

test:
  imports:
    - area_detector_handlers
    - area_detector_handlers.handlers
  requires:
    - pytest
  commands:
    - pytest -v --pyargs area_detector_handlers  # [not win]

about:
  home: https://github.com/bluesky/area-detector-handlers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: DataBroker handlers for Area Detector

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - gwbischof
    - conda-forge/event-model
